
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spinach
    username: root
    password: 
    
mybatis:
    type-aliases-package: com.fatcat.spinach.pojo
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.fatcat.spinachs.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
